name: Rag Pipeline Evaluation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ingest Test Data (Vector DB & BM25)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m src.ingest_db
      # -------------------------
      - name: Run evaluation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: |
          python evaluate.py 

      